#:schema https://raw.githubusercontent.com/xylex-group/xbp-mirrors/refs/heads/main/xbp.project.schema.json
project_name = "tailwind-canonicalize"
version = "0.2.0"
port = 3000
build_dir = "./"
app_type = "library-node"
build_command = "pnpm run build"
install_command = "pnpm install"
target = "library-node"
branch = "main"
version_targets = []
version_domains = []
ignore_paths = []
watch_ignore_paths = []
versioning_disabled = []
release_disabled = []

[[workers]]
name = "tailwind-canonicalize-docs"
root = "apps/docs"
script_name = "tailwind-canonicalize-docs"

[workers.deploy]

[oci]
default_registry = "registry.xbp.app"
owner = "xylex-group"
repository = "xylex-group/tailwind-canonicalize"

[oci.registries."registry.xbp.app"]
provider = "github"
username = "xylex-group"
token_source = "${GITHUB_TOKEN}"

[linear]
default_team_key = "DEV"
organization_name = "suits-formations"

[linear.release]
enabled = true
initiative_ids = ["fd28f67f-8dc8-44b2-bf14-3821ce389145"]
organization_name = "suits-formations"

[github]
repository = "xylex-group/tailwind-canonicalize"

[github.release_branch]
enabled = true
naming_template = "releases/{SERVICE_NAME}-{VERSION}"

[discord]
enabled = true
webhook_url = "${DISCORD_WEBHOOK_URL}"
username = "XBP"

[discord.events]
version_release = true
github_tag = false
github_release = false
crates_io = true
npm = true
linear = true
cargo_dist = true
oci = true
workers_deploy = true
kubernetes_deploy = true
deploy = true
openapi = true
issues = true
commit = true
