// Generated by Blume. Do not edit.
import { defineCollection } from "astro:content";
import { glob } from "astro/loaders";

const docs = defineCollection({
  loader: glob({
    pattern: ["**/*.{md,mdx}","!**/_*","!**/.*","!**/.blume-verify/**","!**/.cache/**","!**/.git/**","!**/.next/**","!**/.turbo/**","!**/.vercel/**","!**/dist/**","!**/node_modules/**"],
    base: "file:///C:/Users/floris/Documents/GitHub/tailwind-canonicalize/apps/docs/docs",
    generateId: ({ entry }) => entry,
  }),
});

export const collections = { docs };
