// Generated by Blume. Do not edit.
import { renderOgImage } from "blume/og";
import data from "blume:data";

export const prerender = true;

// Custom (non-content) pages opted into a generated card, baked in at build.
// The annotation keeps the empty-array case from being an implicit any[]
// (ts(7034)) under a strict tsconfig.
const customRoutes: { slug: string; title: string }[] = [{"slug":"index","title":"tailwind-canonicalize"}];

export function getStaticPaths() {
  const seen = new Set<string>();
  const paths: { params: { slug: string }; props: { title: string } }[] = [];
  const add = (slug: string, title: string) => {
    if (seen.has(slug)) {
      return;
    }
    seen.add(slug);
    paths.push({ params: { slug }, props: { title } });
  };
  // A custom page wins over a content route sharing its path, so add it first.
  for (const route of customRoutes) {
    add(route.slug, route.title);
  }
  for (const route of data.routes) {
    add(route.path === "/" ? "index" : route.path.slice(1), route.title);
  }
  return paths;
}

// Footer branding shared by every card, derived once from the resolved config.
// The repo slug reuses the header link URL; the host comes from the site URL.
const repoSlug = data.config.repoUrl
  ? data.config.repoUrl.split("github.com/")[1]
  : undefined;
const siteHost = (() => {
  if (!data.config.site) {
    return undefined;
  }
  try {
    return new URL(data.config.site).host;
  } catch {
    return undefined;
  }
})();

export async function GET({ props }: { props: { title: string } }) {
  const png = await renderOgImage({
    accent: data.config.og.palette?.accent ?? data.config.theme.accent.light,
    brand: data.config.title,
    description: data.config.description,
    fonts: data.config.og.fonts,
    logo: data.config.og.logo,
    palette: data.config.og.palette,
    repo: repoSlug,
    site: siteHost,
    title: props.title,
  });
  return new Response(new Uint8Array(png), {
    headers: {
      "Cache-Control": "public, max-age=31536000, immutable",
      "Content-Type": "image/png",
    },
  });
}
