import { readFile, writeFile } from "node:fs/promises";
import type { ThemeToken, TokenManifest } from "./types.js";

export interface GenerateThemeOptions {
  outPath: string;
  tokens: Array<{
    name: string;
    value?: string;
    light?: string;
    dark?: string;
    preferVar?: string;
  }>;
  existing?: ThemeToken[];
  preferAppAliases?: boolean;
  /** Emit :root / .dark app variables + @theme inline */
  dualTheme?: boolean;
}

/**
 * Generate Tailwind v4 CSS-first tokens.
 * Prefer aliasing existing app variables; support dual light/dark themes.
 * All utilities remain static class names at call sites — only CSS variables vary by theme.
 */
export function generateThemeCss(options: GenerateThemeOptions): string {
  const prefer = options.preferAppAliases !== false;
  const dual = options.dualTheme === true;
  const lines: string[] = [
    "/* Generated by tailwind-canonicalize — review before committing */",
    "/* Replacements in source must stay complete static utilities (no runtime interpolation). */",
    "",
  ];

  if (dual) {
    lines.push(":root {");
    for (const t of options.tokens) {
      const appName = `--app-${stripColorPrefix(t.name)}`;
      const existing = prefer
        ? findExistingAlias(options.existing ?? [], t.name, t.light ?? t.value ?? "")
        : null;
      if (existing && !existing.startsWith("--app-") && !existing.startsWith("--color-")) {
        // bridge later in @theme
        continue;
      }
      const light = t.light ?? t.value ?? "/* TODO */";
      lines.push(`  ${appName}: ${light};`);
    }
    lines.push("}", "", ".dark {");
    for (const t of options.tokens) {
      if (!t.dark) {
        continue;
      }
      const appName = `--app-${stripColorPrefix(t.name)}`;
      lines.push(`  ${appName}: ${t.dark};`);
    }
    lines.push("}", "", "@theme inline {");
  } else {
    lines.push("@theme {");
  }

  for (const t of options.tokens) {
    const cssName = t.name.startsWith("--")
      ? t.name.startsWith("--color-")
        ? t.name
        : `--color-${t.name.replace(/^--/, "")}`
      : `--color-${t.name}`;

    let value: string;
    if (dual) {
      value = `var(--app-${stripColorPrefix(t.name)})`;
    } else if (prefer && options.existing) {
      const existing = findExistingAlias(
        options.existing,
        t.name,
        t.value ?? t.light ?? "",
      );
      if (existing) {
        value = `var(${existing})`;
      } else if (t.preferVar) {
        value = `var(${t.preferVar})`;
      } else {
        value = t.value ?? t.light ?? "/* TODO: set value */";
      }
    } else if (t.preferVar) {
      value = `var(${t.preferVar})`;
    } else {
      value = t.value ?? t.light ?? "/* TODO: set value */";
    }

    lines.push(`  ${cssName}: ${value};`);
  }

  lines.push("}", "");
  return lines.join("\n");
}

function stripColorPrefix(name: string): string {
  return name.replace(/^--color-/, "").replace(/^--/, "").replace(/^color-/, "");
}

function findExistingAlias(
  existing: ThemeToken[],
  semanticName: string,
  _value: string,
): string | null {
  const bare = stripColorPrefix(semanticName);
  const candidates = [
    `--${bare}`,
    `--app-${bare}`,
    `--color-${bare}`,
    `--${bare.replace(/-/g, "")}`,
  ];
  for (const c of candidates) {
    if (existing.some((t) => t.name === c)) {
      return c;
    }
  }
  const hit = existing.find(
    (t) => t.name.endsWith(bare) || t.name.endsWith(bare.replace(/^color-/, "")),
  );
  return hit?.name ?? null;
}

export function tokensFromManifest(manifest: TokenManifest): Array<{
  name: string;
  value?: string;
  light?: string;
  dark?: string;
  preferVar?: string;
}> {
  const seen = new Set<string>();
  const out: Array<{
    name: string;
    value?: string;
    light?: string;
    dark?: string;
    preferVar?: string;
  }> = [];

  const values = manifest.generateTheme?.values ?? {};

  for (const m of manifest.mappings) {
    if (!m.token) {
      continue;
    }
    const name = m.token.replace(/^--color-/, "").replace(/^--/, "");
    if (seen.has(name)) {
      continue;
    }
    seen.add(name);
    const v = values[name];
    out.push({
      name,
      value: v?.default ?? v?.light,
      light: v?.light ?? v?.default,
      dark: v?.dark,
      preferVar: `--app-${name}`,
    });
  }

  for (const pair of manifest.pairs ?? []) {
    if (!pair.token) {
      continue;
    }
    const name = pair.token.replace(/^--color-/, "").replace(/^--/, "");
    if (seen.has(name)) {
      const existing = out.find((o) => o.name === name);
      if (existing && !existing.dark) {
        existing.dark = values[name]?.dark;
      }
      continue;
    }
    seen.add(name);
    const v = values[name];
    out.push({
      name,
      light: v?.light,
      dark: v?.dark,
      preferVar: `--app-${name}`,
    });
  }

  return out;
}

/**
 * Append or write theme CSS without duplicating existing --color-* vars.
 * Idempotent: second write with same tokens skips existing declarations.
 */
export async function writeThemeCss(
  outPath: string,
  css: string,
  existingCss?: string,
): Promise<{ written: boolean; skipped: string[] }> {
  let current = existingCss;
  if (current === undefined) {
    try {
      current = await readFile(outPath, "utf8");
    } catch {
      current = "";
    }
  }

  const skipped: string[] = [];
  const declRe = /--color-([a-zA-Z0-9-_]+)\s*:/g;
  const existingNames = new Set<string>();
  let m: RegExpExecArray | null = declRe.exec(current);
  while (m) {
    existingNames.add(m[1]!);
    m = declRe.exec(current);
  }

  const lines = css.split("\n");
  const filtered: string[] = [];
  for (const line of lines) {
    const dm = line.match(/--color-([a-zA-Z0-9-_]+)\s*:/);
    if (dm?.[1] && existingNames.has(dm[1])) {
      skipped.push(dm[1]);
      continue;
    }
    filtered.push(line);
  }

  const next = filtered.join("\n").trim();
  if (!next || next === "@theme {\n}" || next === "@theme {}") {
    return { written: false, skipped };
  }

  // If only comments + empty blocks after filter
  if (!/--color-/.test(next) && !/--app-/.test(next)) {
    return { written: false, skipped };
  }

  if (!current.trim()) {
    await writeFile(outPath, `${next}\n`, "utf8");
    return { written: true, skipped };
  }

  await writeFile(outPath, `${current.trimEnd()}\n\n${next}\n`, "utf8");
  return { written: true, skipped };
}

/**
 * Full dual-theme generation from an approved manifest (theme-normalization category).
 */
export function generateDualThemeFromManifest(
  manifest: TokenManifest,
  existing?: ThemeToken[],
): string {
  const tokens = tokensFromManifest(manifest);
  return generateThemeCss({
    outPath: manifest.generateTheme?.path ?? "theme.css",
    tokens,
    existing,
    preferAppAliases: manifest.generateTheme?.preferAppAliases !== false,
    dualTheme: manifest.generateTheme?.dualTheme !== false,
  });
}
